language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.1

addons:
  apt:
    packages:
      - libxml2-utils
      - libglib2.0-dev 

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pkg-config ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pcre       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glib       ; fi
  - Rscript -e 'install.packages("rmarkdown")'
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'devtools::install_github("PolMine/RcppCWB", ref = "dev")'

r_packages:
  - data.table
  - R6
  - pbapply
  - xml2
  - stringi
  - tm
  - knitr
  - tokenizers
  - tidytext
  - covr

warnings_are_errors: false

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'library(covr); codecov(type = c("tests", "vignettes", "examples"), token = "cd301151-effc-4a75-9dc7-bb906dcf4edc")'
